name: github_graphql_client
description: Github client using Github API V4 (GraphQL)
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttericon: ^1.0.7        # Add this dependency.
  gql: ^0.12.3               # Add from here,
  gql_exec: ^0.2.4           # 
  gql_link: ^0.3.0           #  
  gql_http_link: ^0.2.9  
  http: ^0.12.1         # Add this line,
  oauth2: ^1.6.1        # this line,
  url_launcher: ^5.4.10 # and this line.
  window_to_front:       # Add this dependency
    path: '../window_to_front'

dev_dependencies:
  build_runner: ^1.10.0      # And these two,
  gql_build: ^0.0.11  
  pedantic: ^1.9.0

flutter:
  uses-material-design: true